name: test_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  provider: ^6.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_circle_color_picker: ^0.3.0
  flutter_colorpicker: ^1.0.3
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6

dev_dependencies:
  flutter_staggered_grid_view: ^0.6.2
  get: ^4.6.5

  custom_switch: ^0.0.1
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - asset/images/aiLed.png
    - asset/images/ledon.png
    - asset/images/ledon.jpg
    - asset/images/background.jpg
    - asset/images/Reading.png
    - asset/images/memory.png
    - asset/images/ledlogo_1.png
    - asset/images/Relaxation.png
    - asset/images/analysis.png
  fonts:
    - family: Jua
      fonts:
        - asset: asset/font/Jua-Regular.ttf
  uses-material-design: true

